header:
  license:
    spdx-id: BSD-3-Clause
    copyright-owner: Jupyter Development Team
    software-name: eslint-plugin-jupyter
    content: |
      Copyright (c) Jupyter Development Team.
      Distributed under the terms of the Modified BSD License.

  paths-ignore:
    - '**/*.json'
    - '**/*.md'
    - '**/*.svg'
    - '**/*.yml'
    - '**/*.yaml'
    - '**/build'
    - '**/lib'
    - '**/node_modules'
    - '**/static'
    - '**/.*'
    - 'coverage'
    - 'LICENSE'
    - 'yarn.lock'

  comment: on-failure
